package org.gustrb.lexing;

public enum TokenType {
    EOF, OPEN_BRACKETS, CLOSING_BRACKETS, OPEN_BRACES, CLOSING_BRACES, STRING_LITERAL, NUMERIC_LITERAL, SEMI_COLON, COMMA, NULL_TOKEN, BOOLEAN_LITERAL,
}
